[[redirects]]
  from = "/"
  to = "index.html"
  status = 200
  force = true

[[redirects]]
  from = "/thanks"
  to = "thanks.html"
  status = 200
  force = true

[[redirects]]
  from = "/DanielOropeza"
  to = "https://www.fxhash.xyz/u/Daniel%20Oropeza"
  status = 301
  force = true

[[redirects]]
  from = "/DOOM"
  to = "https://www.fxhash.xyz/u/DoomOperator/collection"
  status = 301
  force = true
  
  
[[redirects]]
  from = "/nic"
  to = "https://www.fxhash.xyz/u/nicthib"
  status = 301
  force = true
  
[[redirects]]
  from = "/calicojack"
  to = "https://www.fxhash.xyz/u/calicojack.tez/collection"
  status = 301
  force = true

[[redirects]]
  from = "/Cryptocrystalline"
  to = "https://www.fxhash.xyz/generative/8807"
  status = 301
  force = true

[[redirects]]
  from = "g/*"
  to = "https://www.fxhash.xyz/generative/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://www.fxhash.xyz/u/:splat"
  status = 301
  force = true

