[[redirects]]
  from = "/"
  to = "index.html"
  status = 200
  force = true

[[redirects]]
  from = "/thanks"
  to = "thanks.html"
  status = 200
  force = true

[[redirects]]
  from = "/Gilbster"
  to = "https://www.fxhash.xyz/u/gilbster"
  status = 301
  force = true

[[redirects]]
  from = "/DanielOropeza"
  to = "https://www.fxhash.xyz/u/Daniel%20Oropeza"
  status = 301
  force = true
  
[[redirects]]
  from = "/ChrisRandall"
  to = "https://www.fxhash.xyz/u/Chris%20Randall"
  status = 301
  force = true  

[[redirects]]
  from = "/DOOM"
  to = "https://www.fxhash.xyz/u/DoomOperator/collection"
  status = 301
  force = true  
  
[[redirects]]
  from = "/nic"
  to = "https://www.fxhash.xyz/u/nicthib"
  status = 301
  force = true
  
[[redirects]]
  from = "/calicojack"
  to = "https://www.fxhash.xyz/u/calicojack.tez/collection"
  status = 301
  force = true

[[redirects]]
  from = "/Cryptocrystalline"
  to = "https://www.fxhash.xyz/generative/8807"
  status = 301
  force = true

[[redirects]]
  from = "/spaceplant"
  to = "https://www.fxhash.xyz/generative/10282"
  status = 301
  force = true
  
[[redirects]]
  from = "/CLWBG"
  to = "https://www.fxhash.xyz/generative/10433"
  status = 301
  force = true

[[redirects]]
  from = "/MOBOHASH"
  to = "https://www.fxhash.xyz/generative/10443"
  status = 301
  force = true

[[redirects]]
  from = "/🌺"
  to = "https://www.fxhash.xyz/generative/10979"
  status = 301
  force = true
  
  [[redirects]]
  from = "/xn--3h8h"
  to = "https://www.fxhash.xyz/generative/10979"
  status = 301
  force = true

[[redirects]]
  from = "g/*"
  to = "https://www.fxhash.xyz/generative/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://www.fxhash.xyz/u/:splat"
  status = 301
  force = true

